language: python
cache: pip
python:
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"
services: xvfb
env:
        - QT_QPA_PLATFORM=offscreen
install:
        - pip install -r requirements.txt
        - pip install setuptools_scm
        - python setup.py build
script:
        - xvfb-run -e /dev/stdout -a python -m unittest discover
