language: python
cache: pip
addons:
        apt:
                update: true
                packages:
                        - libxkbcommon-x11-0
python:
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"
install:
        - pip install -r requirements.txt
        - pip install setuptools_scm
        - python setup.py build
script:
        - python -m unittest discover
