[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4",
            "PySide2>=5.12"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "qtimgren/version.py"
